name: Convert Markdown to HTML

on:
  push:
    branches:
      - main # Ensure this matches your default or active branch
    paths:
      - "pages/posts/markdown/*.md" # Updated path to match the correct directory

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install markdown-to-html converter
        run: npm install -g markdown-to-html-cli

      - name: Convert Markdown files to HTML
        run: |
          mkdir -p pages/posts  # Ensure directory exists
          for mdfile in pages/posts/markdown/*.md; do
            htmlfile="pages/posts/$(basename "$mdfile" .md).html"
            markdown-to-html "$mdfile" -o "$htmlfile"
          done

      - name: Commit HTML files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pages/posts/*.html
          git commit -m "Update HTML files from Markdown" -a || echo "No changes to commit"
          git push
